name: uv-publish
description: Build Python package and upload distribution

branding:
  icon: activity
  color: gray-dark

inputs:
  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Check out repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Check out 'dycw/action-uv-publish'
      uses: actions/checkout@v6
      with:
        repository: dycw/action-uv-publish
        fetch-depth: 0
        path: uv-publish

    - name: Install 'uv'
      uses: astral-sh/setup-uv@v7

    - name: Run 'script.py'
      env:
        APP_TOKEN: ${{ inputs.token }}
      run: uv run uv-publish/script.py
      shell: bash
